# This is a basic workflow to help you get started with Actions

name: Deploy NextJS to Ubuntu Server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Stop Running Service
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: sudo kill -9 $(sudo lsof -t -i:3000) ; echo "..." ; cd /var/www/next-app ; rm -r -f *
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
          
      - name: Copy Release folder into Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/nextjs-auto-deploy/nextjs-auto-deploy
          remote: /var/www/next-app
        # This remote directory should be set for full read/write permission
        # sudo chmod 777 /path/to/directory
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
          
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: cd /var/www/next-app ; yarn install;  yarn build ; yarn start    
          
      - name: Start
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: cd /var/www/next-app ; sudo su ubuntu; yarn install;  yarn build ; yarn start
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
